### PR TITLE
I2 io ports

### PR DESCRIPTION
**Pull request by hfenske33**
Issue 2 Change Design (includes handling) of Ports:
- when adding port, they are jumping to the left = internal or right = external side
- ports have a internal/external sign (i/e)
- when moving ports they jump to the nearest edge and change their direction (depends on the edge)
- fix bug: when changing x-size of module, port is fixed to the edge and not outside or somewhere inside, not implemented for the y-size (would be confusing because of overlapping ports)

### CODE REVIEW

**Review by AlexanderKnueppel — COMMENTED** [review]
Looks almost perfect. However, if ports are connected and the type is changed (e.g., from internal to external), the connection still remains... do we want to address that here? A simple solution would be to remove all connections + a warning dialog beforere that all connections get lost (should only popup when connections already exist; similar to the one that opens when a port is removed).
image

**Comment by hfenske33** [comment]
Yes,sounds good. I can then do that on this Branch/Issue.

**Comment by hfenske33** [comment]
Ok -> Remove connections when direction changes (in or out-connections)
Cancel -> doesn't move the port

**Comment by AlexanderKnueppel** [comment]
If your are finnished, we can merge this branch into develop.

**Pull request merged**
